// Auto-generated by sanitizeGeneratedFiles
export async function onRequest(context) {
  const templates = [
    { id: 1, name: 'Professional', description: 'A clean and professional template.' },
    { id: 2, name: 'Creative', description: 'A modern and creative template.' },
  ];
  return new Response(JSON.stringify(templates), {
    headers: { 'Content-Type': 'application/json' },
  });
}

export async function onRequest(context) {
  const { request } = context;
  if (request.method !== 'POST') {
    return new Response('Method Not Allowed', { status: 405 });
  }
  try {
    const userData = await request.json();
    saveUserDataToDatabase(userData);
    return new Response('User data saved successfully', { status: 200 });
  } catch (error) {
    return new Response('Internal Server Error', { status: 500 });
  }
}
function saveUserDataToDatabase(userData) {
  console.log('User data saved:', userData);
}

export async function onRequest(context) {
  const { request } = context;
  const url = new URL(request.url);
  const userId = url.searchParams.get('userId');
  if (!userId) {
    return new Response('Bad Request', { status: 400 });
  }
  try {
    const userData = getUserDataFromDatabase(userId);
    return new Response(JSON.stringify(userData), {
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (error) {
    return new Response('Internal Server Error', { status: 500 });
  }
}
function getUserDataFromDatabase(userId) {
  return { userId, name: 'John Doe', email: 'john.doe@example.com' };
}