name = "73ab85b3-c057-435d-af59-6a48fbe73098"
account_id = "6ec57290cbb52c27cda0bd089bae05a0"
compatibility_date = "2024-01-01"
main = "functions/index.ts"
usage_model = "bundled"

[site]
bucket = "./public"

[env.production]
workers_dev = true